### ISSUE TITLE
The `Tab` at the end of a table stopped working.

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-table#67]
The tab in the last table cell should insert another row in a table.

This stopped working on latest master.

**Comment by jodator** [comment]
Error in console:
```
Uncaught CKEditorError: view-writer-cannot-break-ui-element
    at Writer._breakAttributes (http://localhost:8125/ckeditor5-table/tests/manual/table.js:34036:10)
    at Writer.insert (http://localhost:8125/ckeditor5-table/tests/manual/table.js:33282:34)
    at createTableSection (http://localhost:8125/ckeditor5-table/tests/manual/table.js:79385:23)
    at getOrCreateTableSection (http://localhost:8125/ckeditor5-table/tests/manual/table.js:79360:47)
    at DowncastDispatcher.dispatcher.on (http://localhost:8125/ckeditor5-table/tests/manual/table.js:79026:25)
    at DowncastDispatcher.fire (http://localhost:8125/ckeditor5-table/tests/manual/table.js:3338:29)
    at DowncastDispatcher._testAndFire (http://localhost:8125/ckeditor5-table/tests/manual/table.js:37270:8)
    at DowncastDispatcher.convertInsert (http://localhost:8125/ckeditor5-table/tests/manual/table.js:36987:9)
    at DowncastDispatcher.convertChanges (http://localhost:8125/ckeditor5-table/tests/manual/table.js:36946:10)
    at view.change.writer (http://localhost:8125/ckeditor5-table/tests/manual/table.js:45354:29)
```

**Comment by Reinmar** [comment]
There are no UI elements in use now. Aren't you testing this on your upcoming PR with selection handle?
